ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_network_os: dellemc.enterprise_sonic.sonic
ansible_password: YourPaSsWoRd
ansible_user: admin
bgp_asn: '{{ host_data[inventory_hostname].bgp_asn }}'
bgp_router_id: '{{ host_data[inventory_hostname].bgp_router_id }}'
host_data:
  DC2-R1L1:
    bgp_asn: 65201
    bgp_router_id: 10.2.2.1
    loopback0_ip: 10.2.2.1/32
    loopback1_ip: 1.2.1.1/32
    loopback3_ip: 1.12.1.1/32
    mclag_peer_ip: 10.2.2.2
    mgmt_gateway_ip: 192.168.1.1
    mgmt_ip: 192.168.1.210/24
    vtep_name: vtep_DC2R1
    eth1/5: 10.10.2.1/30 
  DC2-R1L2:
    bgp_asn: 65201
    bgp_router_id: 10.2.2.2
    loopback0_ip: 10.2.2.2/32
    loopback1_ip: 1.2.1.1/32
    loopback3_ip: 1.12.1.2/32
    mclag_peer_ip: 10.2.2.1
    mgmt_gateway_ip: 192.168.1.1
    mgmt_ip: 192.168.1.211/24
    vtep_name: vtep_DC2R1
    eth1/5: 10.10.2.5/30 
  DC2-R2L1:
    bgp_asn: 65202
    bgp_router_id: 10.2.2.3
    loopback0_ip: 10.2.2.3/32
    loopback1_ip: 1.2.1.2/32
    mclag_peer_ip: 10.2.2.4
    mgmt_gateway_ip: 192.168.1.1
    mgmt_ip: 192.168.1.214/24
    vtep_name: vtep_DC2R2
  DC2-R2L2:
    bgp_asn: 65202
    bgp_router_id: 10.2.2.4
    loopback0_ip: 10.2.2.4/32
    loopback1_ip: 1.2.1.2/32
    mclag_peer_ip: 10.2.2.3
    mgmt_gateway_ip: 192.168.1.1
    mgmt_ip: 192.168.1.215/24
    vtep_name: vtep_DC2R2
  DC2-S1:
    bgp_asn: 65200
    bgp_router_id: 10.2.1.1
    loopback0_ip: 10.2.1.1/32
    mgmt_gateway_ip: 192.168.1.1
    mgmt_ip: 192.168.1.216/24
  DC2-S2:
    bgp_asn: 65200
    bgp_router_id: 10.2.1.2
    loopback0_ip: 10.2.1.2/32
    mgmt_gateway_ip: 192.168.1.1
    mgmt_ip: 192.168.1.217/24
loopback0_ip: '{{ host_data[inventory_hostname].loopback0_ip }}'
loopback_inf0: Loopback0
loopback_inf1: Loopback1
loopback_inf3: Loopback3
mgmt_gateway_ip: '{{ host_data[inventory_hostname].mgmt_gateway_ip }}'
mgmt_ip: '{{ host_data[inventory_hostname].mgmt_ip }}'
sonic_bgp_external_pg_entry:
    advertisement_interval: 0
    bfd:
      enabled: true
    capability:
      extended_nexthop: true
    name: external
    remote_as:
      peer_type: external
    timers:
      holdtime: 9
      keepalive: 3
    address_family:
      afis:
        - activate: true
          afi: ipv4
          safi: unicast
        - activate: true
          afi: l2vpn
          safi: evpn
sonic_bgp_fabriclink_neighbors_aflist:
  - activate: true
    afi: ipv4
    allowas_in:
      value: 2
    safi: unicast
  - activate: true
    afi: l2vpn
    safi: evpn
sonic_bgp_spineleaf_peergroup:
  advertisement_interval: 5
  bfd:
    enabled: true
  capability:
    extended_nexthop: true
  name: spine-leaf
  remote_as:
    peer_type: external
  timers:
    holdtime: 9
    keepalive: 3
vlan_info:
  61:
    neigh_suppress: true
    vni: 2061
    vrf: VrfTenant1
  62:
    neigh_suppress: true
    vni: 2062
    vrf: VrfTenant2
  100:
    anycast_gateway_ip: 172.16.0.254/24
    neigh_suppress: true
    vni: 20100
    vrf: VrfTenant1
  200:
    anycast_gateway_ip: 172.16.1.254/24
    neigh_suppress: true
    vni: 20200
    vrf: VrfTenant1
  201:
    anycast_gateway_ip: 172.16.2.254/24
    neigh_suppress: true
    vni: 20201
    vrf: VrfTenant1
  202:
    anycast_gateway_ip: 172.16.3.254/24
    neigh_suppress: true
    vni: 20202
    vrf: VrfTenant1
  301:
    anycast_gateway_ip: 172.16.4.254/24
    neigh_suppress: true
    vni: 20301
    vrf: VrfTenant1
  302:
    anycast_gateway_ip: 172.16.5.254/24
    neigh_suppress: true
    vni: 20302
    vrf: VrfTenant1
  303:
    anycast_gateway_ip: 172.16.6.254/24
    neigh_suppress: true
    vni: 20303
    vrf: VrfTenant1
  304:
    anycast_gateway_ip: 172.16.7.254/24
    neigh_suppress: true
    vni: 20304
    vrf: VrfTenant1
  305:
    anycast_gateway_ip: 172.16.8.254/24
    neigh_suppress: true
    vni: 20305
    vrf: VrfTenant1
  306:
    anycast_gateway_ip: 172.16.9.254/24
    neigh_suppress: true
    vni: 20306
    vrf: VrfTenant2
  307:
    anycast_gateway_ip: 172.16.10.254/24
    neigh_suppress: true
    vni: 20307
    vrf: VrfTenant2
  308:
    anycast_gateway_ip: 172.16.11.254/24
    neigh_suppress: true
    vni: 20308
    vrf: VrfTenant2
  309:
    anycast_gateway_ip: 172.16.12.254/24
    neigh_suppress: true
    vni: 20309
    vrf: VrfTenant2
  310:
    anycast_gateway_ip: 172.16.13.254/24
    neigh_suppress: true
    vni: 20310
    vrf: VrfTenant2
