is_border_leaf: false
lacp_pcs: []
mclag_member_pcs: []
sonic_bgp:
  - bestpath:
      as_path:
        multipath_relax: true
    bgp_as: '{{ bgp_asn }}'
    router_id: '{{ bgp_router_id }}'
  - bgp_as: '{{bgp_asn}}'
    vrf_name: VrfTenant1
  - bgp_as: '{{bgp_asn}}'
    vrf_name: VrfTenant2
  - bgp_as: '{{ bgp_asn }}'
sonic_bgp_af:
  - address_family:
      afis:
        - afi: ipv4
          max_path:
            ebgp: 16
          redistribute:
            - protocol: connected
          safi: unicast
        - advertise_all_vni: true
          afi: l2vpn
          safi: evpn
    bgp_as: '{{bgp_asn}}'
  - address_family:
      afis:
        - afi: l2vpn
          route_advertise_list:
            - advertise_afi: ipv4
          safi: evpn
        - afi: ipv4
          redistribute:
            - protocol: connected
          safi: unicast
    bgp_as: '{{ bgp_asn }}'
    vrf_name: VrfTenant1
  - address_family:
      afis:
        - afi: l2vpn
          route_advertise_list:
            - advertise_afi: ipv4
          safi: evpn
        - afi: ipv4
          redistribute:
            - protocol: connected
          safi: unicast
    bgp_as: '{{ bgp_asn }}'
    vrf_name: VrfTenant2
sonic_bgp_neighbors:
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - neighbor: Eth1/6
        peer_group: spine-leaf
      - neighbor: Eth1/7
        peer_group: spine-leaf
    peer_group:
      - '{{sonic_bgp_spineleaf_peergroup}}'
      - '{{sonic_bgp_external_pg_entry}}'
sonic_bgp_neighbors_af:
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - address_family: '{{sonic_bgp_fabriclink_neighbors_aflist}}'
        neighbor: Eth1/6
      - address_family: '{{sonic_bgp_fabriclink_neighbors_aflist}}'
        neighbor: Eth1/7
sonic_config:
  lines: []
sonic_interfaces:
  - description: '"Uplink to DC1-S1"'
    enabled: true
    name: Eth1/6
  - description: '"Uplink to DC1-S2"'
    enabled: true
    name: Eth1/7
  - description: '"MCLAG"'
    enabled: true
    name: Eth1/8
  - description: '"MCLAG"'
    enabled: true
    name: Eth1/9
  - description: router-id
    name: '{{ loopback_inf0 }}'
  - description: vtep
    name: '{{ loopback_inf1 }}'
sonic_l2_interfaces:
  - name: PortChannel100
    trunk:
      allowed_vlans:
        - vlan: 100
        - vlan: 200
        - vlan: 201
        - vlan: 202
        - vlan: 301
        - vlan: 302
        - vlan: 303
        - vlan: 304
        - vlan: 305
        - vlan: 306
        - vlan: 307
        - vlan: 308
        - vlan: 309
        - vlan: 310
        - vlan: 61
        - vlan: 62
sonic_l3_interfaces:
  - name: Eth1/6
    ipv6:
      enabled: true
  - name: Eth1/7
    ipv6:
      enabled: true
  - name: '{{ loopback_inf0 }}'
    ipv4:
      addresses:
        - address: '{{ loopback0_ip }}'
  - name: '{{ loopback_inf1 }}'
    ipv4:
      addresses:
        - address: '{{ loopback1_ip }}'
  - name: Vlan100
    ipv4:
      anycast_addresses: 172.16.0.254/24
  - name: Vlan200
    ipv4:
      anycast_addresses: 172.16.1.254/24
  - name: Vlan201
    ipv4:
      anycast_addresses: 172.16.2.254/24
  - name: Vlan202
    ipv4:
      anycast_addresses: 172.16.3.254/24
  - name: Vlan301
    ipv4:
      anycast_addresses: 172.16.4.254/24
  - name: Vlan302
    ipv4: 
      anycast_addresses: 172.16.5.254/24
  - name: Vlan303
    ipv4:
      anycast_addresses: 172.16.6.254/24
  - name: Vlan304
    ipv4:
      anycast_addresses: 172.16.7.254/24
  - name: Vlan305
    ipv4:
      anycast_addresses: 172.16.8.254/24
  - name: Vlan306
    ipv4:
      anycast_addresses: 172.16.9.254/24
  - name: Vlan307
    ipv4:
      anycast_addresses: 172.16.10.254/24
  - name: Vlan308
    ipv4:
      anycast_addresses: 172.16.11.254/24
  - name: Vlan309
    ipv4:
      anycast_addresses: 172.16.12.254/24
  - name: Vlan310
    ipv4:
      anycast_addresses: 172.16.13.254/24
sonic_lag_interfaces:
  - members:
      interfaces:
        - member: Eth1/8
        - member: Eth1/9
    name: PortChannel100
sonic_system:
  anycast_address:
    ipv4: true
    mac_address: '{{ anycast_mac_address }}'
  hostname: DC2-R2L2
  interface_naming: standard
sonic_vlans:
  - vlan_id: 3000
    description: "External"
  - vlan_id: 100
    description: "Management"
  - vlan_id: 200
    description: "vMotion"
  - vlan_id: 201
    description: "SAN-A"
  - vlan_id: 202
    description: "SAN-B"
  - vlan_id: 301
    description: "VM1-VRF1"
  - vlan_id: 302
    description: "VM2-VRF1"
  - vlan_id: 303
    description: "VM2-VRF1"
  - vlan_id: 304
    description: "VM2-VRF1"
  - vlan_id: 305
    description: "VM2-VRF1"
  - vlan_id: 306
    description: "VM1-VRF2"
  - vlan_id: 307
    description: "VM2-VRF2"
  - vlan_id: 308
    description: "VM3-VRF2"
  - vlan_id: 309
    description: "VM4-VRF2"
  - vlan_id: 310
    description: "VM5-VRF2"
  - vlan_id: 61
    description: "VRF1 Routing"
  - vlan_id: 62
    description: "VRF2 Routing"
sonic_vrf_interfaces:
  - members:
      interfaces:
        - name: Vlan100
        - name: Vlan61
        - name: Vlan200
        - name: Vlan201
        - name: Vlan202
        - name: Vlan301
        - name: Vlan302
        - name: Vlan303
        - name: Vlan304
        - name: Vlan305
    name: VrfTenant1
  - members:
      interfaces:
        - name: Vlan62
        - name: Vlan306
        - name: Vlan307
        - name: Vlan308
        - name: Vlan309
        - name: Vlan310
    name: VrfTenant2
sonic_vxlans:
  - evpn_nvo: nvo1
    name: vtep_DC2R2
    source_ip: '{{ loopback1_ip.split(''/'')[0] }}'
    vlan_map:
      - vlan: 100
        vni: 20100
      - vlan: 200
        vni: 20200
      - vlan: 201
        vni: 20201
      - vlan: 202
        vni: 20202
      - vlan: 301
        vni: 20301
      - vlan: 302
        vni: 20302
      - vlan: 303
        vni: 20303
      - vlan: 304
        vni: 20304
      - vlan: 305
        vni: 20305
      - vlan: 306
        vni: 20306
      - vlan: 307
        vni: 20307
      - vlan: 308
        vni: 20308
      - vlan: 309
        vni: 20309
      - vlan: 310
        vni: 20310
      - vlan: 61
        vni: 2061
      - vlan: 62
        vni: 2062
    vrf_map:
      - vni: 2061
        vrf: VrfTenant1
      - vni: 2062
        vrf: VrfTenant2
vlans:
  - 100
  - 200
  - 201
  - 202
  - 301
  - 302
  - 303
  - 304
  - 305
  - 306
  - 307
  - 308
  - 309
  - 310
vrfs:
  - VrfTenant1
  - VrfTenant2
